### PR TITLE
EthCore 1.0.9

### PR DESCRIPTION
**Pull request by wjmelements**
#### Changes
This is an alternative to https://github.com/uport-project/UPTEthereumSigner/pull/34 that keeps CoreEthereum but removes the unused references to POSIX APIs Apple doesn't want us to use.
Tests pass.
I do not have access to the podspec for CoreEthereum so I refer to the pod by commit and git url.
Reviewers @joshuabell @aldigjo

### CODE REVIEW

**Comment by aldigjo** [comment]
@wjmelements Just to make sure, when I install this branch of UPTEthereumSigner to try It out, I still see the async files present. Unless I'm misinterpreting something it shouldn't be present in your fork either right? Thanks for the help on this! 

https://github.com/wjmelements/UPTEthereumSigner/tree/master/Pods/CoreEthereum/openssl/src/crypto/async

**Comment by aldigjo** [comment]
Should the header files be removed as well? @wjmelements 
https://github.com/wjmelements/UPTEthereumSigner/tree/core-ethereum-1.0.6/Pods/CoreEthereum/openssl/src/crypto/async

**Comment by aldigjo** [comment]
Also I'm still seeing CoreEthereum 1.0.4 being installed, possibly because of the podspec? https://github.com/wjmelements/UPTEthereumSigner/blob/core-ethereum-1.0.6/UPTEthereumSigner.podspec#L43

**Comment by joshuabell** [comment]
@aldigjo to get CoreEthereum 1.0.6 you may have to run 'pod install'. Also, I'd recommend favoring this pull request over #34 

@wjmelements do you know who has access to the CoreEthereum podspec?

**Comment by wjmelements** [comment]
`william.morriss@consensys.net` owns the podspec, and my only pod session with that email has expired. If I don't get ownership of the pod I'll have to rename it.

I have pushed 1.0.7, which removes those headers.

**Comment by wjmelements** [comment]
@aldigjo https://stackoverflow.com/questions/22447062/how-do-i-create-a-cocoapods-podspec-that-has-a-dependency-that-exists-outside-of
We'll have to work around podspec ownership in order to fix that, probably by renaming the CoreEthereum pod.

**Comment by wjmelements** [comment]
Creating a new podspec, EthCore

**Comment by wjmelements** [comment]
Renamed and pushed with new podspec

**Review by aldigjo — APPROVED** [review]

**Pull request merged**
