### PR TITLE
Remove EthCore from spec frameworks

### PR DESCRIPTION
**Pull request by aldigjo**

### CODE REVIEW

**Comment by wjmelements** [comment]
Have you tried installing the pod with this change?

**Comment by aldigjo** [comment]
@wjmelements yes, maybe you could help me understand why EthCore was included there, because I was getting Framework not found in a react-native project, is there a missing search path to use instead?

**Comment by aldigjo** [comment]
I assumed its not necessary since it is being used as a pod anyway?

**Comment by wjmelements** [comment]
EthCore is a dependency of UPTEthereumSigner that provides much of the crypto. I forked EthCore from CoreBitcoin, the prior dependency, and removed much of the bitcoin-specific material. I also replaced the OpenSSL binary with platform-independent source code, which allows the UPTEthereumSigner unit tests to run on a simulator, and pruned the included openssl, removing unnecessary parts.

**Comment by wjmelements** [comment]
It's been over a year, so I don't remember specifics on how this builds, or why I also included it as a framework, but a lot of issues were related to EthCore being a recursive dependency. It is important that when UPTEthereumSigner builds it has access to the EthCore framework.

**Comment by jasheal** [comment]
Removing `EthCore` from `s.frameworks` builds fine on my end in a new project and also resolves our build and linking issues with Xcode11. Having it there forces us to pass in the `use_frameworks!` flag to projects using `react-native-uport-signer`. This causes a bunch of other compatibility issues with other dependencies. (RN60+, XCode 11)

**Review by pelle — APPROVED** [review]
LGTM

**Pull request merged**
